import type { Affirmation, Category } from "@/types";

export const CATEGORIES: Category[] = [
  {
    "id": "1",
    "name": "Confidence",
    "slug": "confidence",
    "description": "Steady self-belief",
    "icon": "🌿",
    "color": "#4a7c68",
    "sort_order": 1
  },
  {
    "id": "2",
    "name": "Self-Love",
    "slug": "self-love",
    "description": "Kindness toward yourself",
    "icon": "💗",
    "color": "#c45c7a",
    "sort_order": 2
  },
  {
    "id": "3",
    "name": "Calm",
    "slug": "anxiety",
    "description": "Ease and safety",
    "icon": "🌊",
    "color": "#5a8a9e",
    "sort_order": 3
  },
  {
    "id": "4",
    "name": "Motivation",
    "slug": "motivation",
    "description": "Gentle drive",
    "icon": "☀️",
    "color": "#c49a5c",
    "sort_order": 4
  },
  {
    "id": "5",
    "name": "Gratitude",
    "slug": "gratitude",
    "description": "Noticing the good",
    "icon": "🙏",
    "color": "#7a9e5a",
    "sort_order": 5
  },
  {
    "id": "6",
    "name": "Success",
    "slug": "success",
    "description": "Progress and purpose",
    "icon": "✨",
    "color": "#8a7ac4",
    "sort_order": 6
  },
  {
    "id": "7",
    "name": "Relationships",
    "slug": "relationships",
    "description": "Connection and care",
    "icon": "🤝",
    "color": "#c47a9a",
    "sort_order": 7
  },
  {
    "id": "8",
    "name": "Health",
    "slug": "health",
    "description": "Body and energy",
    "icon": "🌱",
    "color": "#5a9e7a",
    "sort_order": 8
  },
  {
    "id": "9",
    "name": "Resilience",
    "slug": "resilience",
    "description": "Bounce back",
    "icon": "🛡️",
    "color": "#6a7ab4",
    "sort_order": 9
  },
  {
    "id": "10",
    "name": "Mindfulness",
    "slug": "mindfulness",
    "description": "Present moment",
    "icon": "🧘",
    "color": "#5a9aaa",
    "sort_order": 10
  }
];

const cat = (slug: string) => CATEGORIES.find((c) => c.slug === slug)!;

/** Full system library — free sees a subset; full practice unlocks all */
export const ALL_AFFIRMATIONS: Affirmation[] = [
  { id: "a1", content: "I am confident in my abilities and trust myself completely.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a2", content: "I speak with clarity and my voice matters.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a3", content: "I trust my intuition and make decisions with ease.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a4", content: "I am becoming more confident every single day.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a5", content: "I walk into rooms knowing I belong here.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a6", content: "My presence is enough. I do not need to prove myself.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a7", content: "I handle challenges with a steady mind and an open heart.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a8", content: "I am proud of how far I have already come.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a9", content: "I trust the wisdom I have earned through experience.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a10", content: "I can learn what I do not yet know.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a11", content: "I stand by my values even when it is hard.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a12", content: "I am allowed to take up space.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a13", content: "I share my ideas without shrinking.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a14", content: "I recover quickly from awkward moments.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a15", content: "I am comfortable being seen as I am.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a16", content: "I choose courage over perfect certainty.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a17", content: "I believe in my capacity to grow.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a18", content: "I am solid in who I am becoming.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a19", content: "I give myself credit for trying.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a20", content: "I am not behind. I am on my path.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a21", content: "I trust my judgment in important choices.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a22", content: "I can disagree without losing my center.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a23", content: "I am worthy of opportunities that stretch me.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a24", content: "I show up prepared and open.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a25", content: "I let my work speak without constant self-doubt.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a26", content: "I am calm under pressure more often than not.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a27", content: "I ask for what I need with respect.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a28", content: "I am enough for the challenges I face.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a29", content: "I replace harsh self-talk with honest encouragement.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a30", content: "I carry quiet confidence into new situations.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a31", content: "I honor my strengths without apology.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a32", content: "I am learning to trust myself more each week.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a33", content: "I do not need everyone's approval to move forward.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a34", content: "I am capable of clear, kind leadership.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a35", content: "I face hard conversations with composure.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a36", content: "I am grounded when others are uncertain.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a37", content: "I celebrate competence without arrogance.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a38", content: "I am free to change my mind with new information.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a39", content: "I hold myself with dignity in success and failure.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a40", content: "I am becoming the person I can rely on.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a41", content: "I trust my pace and my process.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a42", content: "I am confident in small steps and big leaps.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a43", content: "I own my story without shame.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a44", content: "I am steady when I advocate for myself.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a45", content: "I welcome feedback without collapsing.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a46", content: "I know my worth is not up for debate.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a47", content: "I move through doubt and still take action.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a48", content: "I am proud of my effort, not only outcomes.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a49", content: "I choose self-respect in how I speak and act.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a50", content: "I am confident that I can figure things out.", category_id: "1", is_system: true, language: "en", tags: ["confidence"], category: cat("confidence") },
  { id: "a51", content: "I am enough exactly as I am right now.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a52", content: "I treat myself with the same kindness I give others.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a53", content: "I am worthy of love, respect, and happiness.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a54", content: "I forgive myself and release what no longer serves me.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a55", content: "My body is my home and I care for it with love.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a56", content: "I speak to myself the way I would speak to someone I love.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a57", content: "I allow myself to rest without guilt.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a58", content: "I am allowed to take up space and have needs.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a59", content: "I accept my imperfect, whole self.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a60", content: "I am patient with my healing.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a61", content: "I deserve gentleness on hard days.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a62", content: "I do not have to earn rest or joy.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a63", content: "I am friendly toward my own mind.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a64", content: "I release comparison and return to my path.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a65", content: "I am allowed to say no to protect my peace.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a66", content: "I care for myself as a daily practice.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a67", content: "I am worthy of my own attention.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a68", content: "I hold my flaws with softness.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a69", content: "I am not a project to be fixed. I am a person to be lived.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a70", content: "I choose compassion when I make mistakes.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a71", content: "I am learning to like my own company.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a72", content: "I honor my feelings without drowning in them.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a73", content: "I am allowed to change and still be me.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a74", content: "I give myself the benefit of the doubt.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a75", content: "I am deserving of good things without proving it.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a76", content: "I nurture the parts of me that feel tender.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a77", content: "I am home in my own skin a little more each day.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a78", content: "I stop abandoning myself to please others.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a79", content: "I am kind in the mirror and in my thoughts.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a80", content: "I celebrate who I am, not only who I might become.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a81", content: "I allow pleasure and play without justifying them.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a82", content: "I am worthy of support when I struggle.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a83", content: "I treat my inner child with patience.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a84", content: "I am whole even while I am still growing.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a85", content: "I choose words that soothe rather than scold.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a86", content: "I am allowed to grieve what I needed and did not get.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a87", content: "I respect my limits as wisdom, not weakness.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a88", content: "I am loving toward myself in private.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a89", content: "I release the need to be endlessly productive.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a90", content: "I am a good friend to myself.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a91", content: "I accept compliments and let them land.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a92", content: "I am soft with my body and its seasons.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a93", content: "I deserve relationships that feel reciprocal.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a94", content: "I am patient with old patterns as I change them.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a95", content: "I include myself in the circle of care I offer others.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a96", content: "I am allowed to want more for my life.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a97", content: "I heal at a pace that honors my nervous system.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a98", content: "I am proud of the care I show myself today.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a99", content: "I choose self-respect over self-punishment.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a100", content: "I am enough, including on ordinary days.", category_id: "2", is_system: true, language: "en", tags: ["self-love"], category: cat("self-love") },
  { id: "a101", content: "I am safe in this moment. I breathe in calm and exhale tension.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a102", content: "I release worry and choose peace instead.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a103", content: "My thoughts do not control me. I can return to the present.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a104", content: "This feeling will pass. I am steady through it.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a105", content: "I soften my shoulders and unclench my jaw. I am here.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a106", content: "I meet uncertainty with curiosity, not fear.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a107", content: "One breath at a time is enough.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a108", content: "I am grounded. My feet are on the floor. I am okay.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a109", content: "I let anxious thoughts float by without chasing them.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a110", content: "I am larger than this wave of worry.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a111", content: "I create safety in my body with slow breath.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a112", content: "I do not need to solve everything right now.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a113", content: "I am allowed to pause when I feel overwhelmed.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a114", content: "I return to what I can control today.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a115", content: "I am calm enough to take the next small step.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a116", content: "I release the need to predict every outcome.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a117", content: "I am present, not trapped in what-ifs.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a118", content: "I soothe my nervous system with kindness.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a119", content: "I am safe to feel and still be okay.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a120", content: "I choose a slower pace when anxiety rises.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a121", content: "I am not my anxious thoughts.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a122", content: "I breathe space around tight places in my chest.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a123", content: "I can ask for help when worry is loud.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a124", content: "I ground myself in sight, sound, and touch.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a125", content: "I allow calm to return in waves.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a126", content: "I am steady enough for this moment only.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a127", content: "I release tension I do not need to carry.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a128", content: "I trust that most fears are larger than the facts.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a129", content: "I am gentle with myself when my mind races.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a130", content: "I come back to now, again and again.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a131", content: "I am learning that calm can coexist with not knowing.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a132", content: "I give my body permission to settle.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a133", content: "I replace catastrophe stories with what is true now.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a134", content: "I am capable of weathering uncomfortable feelings.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a135", content: "I rest my mind on simple, present facts.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a136", content: "I am not alone inside this feeling.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a137", content: "I choose peace as a practice, not a performance.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a138", content: "I am safe to slow down.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a139", content: "I let the breath lead when thoughts speed up.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a140", content: "I hold anxiety with care, not criticism.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a141", content: "I am rooted even when emotions move.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a142", content: "I do one thing at a time with full attention.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a143", content: "I am allowed to step away and reset.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a144", content: "I trust my ability to cope with what comes.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a145", content: "I soften the edges of my fear with breath.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a146", content: "I am here, alive, and breathing on purpose.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a147", content: "I release the grip of urgency when it is false.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a148", content: "I am calm in my center even if the day is busy.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a149", content: "I meet panic with a plan: pause, breathe, proceed.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a150", content: "I am okay in this exact second.", category_id: "3", is_system: true, language: "en", tags: ["anxiety"], category: cat("anxiety") },
  { id: "a151", content: "I take consistent action toward my goals every day.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a152", content: "I begin where I am, with what I have.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a153", content: "Progress, not perfection, moves me forward.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a154", content: "I show up for myself even when motivation is quiet.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a155", content: "Small steps still count. I take the next one.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a156", content: "I am capable of hard things, one focused moment at a time.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a157", content: "Discipline is a form of self-respect. I honor my commitments.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a158", content: "I finish what I start, or I adjust with honesty.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a159", content: "I start before I feel fully ready.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a160", content: "I protect time for what matters most.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a161", content: "I am building momentum with today's effort.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a162", content: "I choose action over endless planning.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a163", content: "I can do difficult work in short, focused bursts.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a164", content: "I return to my goals after distraction.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a165", content: "I am motivated by meaning, not only pressure.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a166", content: "I make the next right move, however small.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a167", content: "I am consistent more than I am intense.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a168", content: "I fuel my effort with rest and clarity.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a169", content: "I am willing to be a beginner again.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a170", content: "I keep promises I make to myself.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a171", content: "I turn intention into a single clear task.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a172", content: "I am energized by progress I can see.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a173", content: "I remove one obstacle at a time.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a174", content: "I work with focus and then truly stop.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a175", content: "I am driven by curiosity as much as ambition.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a176", content: "I show up on ordinary days, not only inspired ones.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a177", content: "I break big goals into kind, doable pieces.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a178", content: "I am patient with the lag between effort and results.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a179", content: "I choose environments that support my focus.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a180", content: "I am the kind of person who follows through.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a181", content: "I restart without drama when I slip.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a182", content: "I invest energy where it compounds.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a183", content: "I am motivated by the life I am building.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a184", content: "I act in alignment with my future self.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a185", content: "I replace 'someday' with a time on the calendar.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a186", content: "I am capable of sustained, gentle effort.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a187", content: "I prioritize depth over scattered busyness.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a188", content: "I finish today's essential task with care.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a189", content: "I am not waiting for perfect conditions.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a190", content: "I use structure to free my creativity.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a191", content: "I celebrate starting, not only finishing.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a192", content: "I stay with the work a little longer than comfort.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a193", content: "I am building trust with myself through action.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a194", content: "I choose progress that is sustainable.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a195", content: "I clear space so important work can happen.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a196", content: "I am motivated by service as well as success.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a197", content: "I return to the plan after rest.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a198", content: "I do what I said I would, especially when it is quiet.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a199", content: "I am forward-moving, even in small ways.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a200", content: "I begin now.", category_id: "4", is_system: true, language: "en", tags: ["motivation"], category: cat("motivation") },
  { id: "a201", content: "I am grateful for all the abundance already in my life.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a202", content: "I notice small good things and let them land.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a203", content: "Thank you for this breath, this day, this chance to begin again.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a204", content: "I appreciate the people who make my life warmer.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a205", content: "There is enough goodness here for me to notice today.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a206", content: "I receive simple joys without needing to earn them.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a207", content: "I am thankful for a body that carries me.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a208", content: "I notice comfort, safety, and ordinary grace.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a209", content: "I am grateful for lessons wrapped in hard days.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a210", content: "I appreciate clean water, food, and shelter when I have them.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a211", content: "I thank the version of me that kept going.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a212", content: "I am open to noticing beauty on the way.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a213", content: "I appreciate honest conversations and true friends.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a214", content: "I am grateful for time to rest when it comes.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a215", content: "I notice the kindness of strangers and let it matter.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a216", content: "I am thankful for growth I once thought impossible.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a217", content: "I appreciate the work that sustains me.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a218", content: "I am grateful for laughter that breaks tension.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a219", content: "I thank my senses for connecting me to the world.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a220", content: "I appreciate second chances and new mornings.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a221", content: "I am grateful for the quiet between tasks.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a222", content: "I notice abundance in skills, memories, and care.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a223", content: "I appreciate technology that keeps me connected.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a224", content: "I am thankful for nature when I can access it.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a225", content: "I receive compliments with a simple thank you.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a226", content: "I am grateful for the people who taught me.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a227", content: "I appreciate progress that does not need an audience.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a228", content: "I am thankful for music, stories, and art that move me.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a229", content: "I notice the privilege of choice where I have it.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a230", content: "I am grateful for a mind that can learn and change.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a231", content: "I appreciate warm meals and shared tables.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a232", content: "I am thankful for health in whatever measure I have today.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a233", content: "I notice love in its quiet forms.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a234", content: "I am grateful for the ability to begin again after mistakes.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a235", content: "I appreciate honesty, including my own.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a236", content: "I am thankful for tools and teachers that help me grow.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a237", content: "I notice peace when it arrives and name it.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a238", content: "I am grateful for the roof over my head.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a239", content: "I appreciate the energy I have for what matters.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a240", content: "I am thankful for boundaries that protect connection.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a241", content: "I notice small wins and store them as fuel.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a242", content: "I am grateful for the chance to care for someone else.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a243", content: "I appreciate seasons of slowing down.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a244", content: "I am thankful for curiosity that keeps life interesting.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a245", content: "I receive today's gifts without minimizing them.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a246", content: "I am grateful for the path behind me and ahead.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a247", content: "I appreciate community, online or near.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a248", content: "I am thankful for moments of ease.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a249", content: "I notice grace in ordinary routines.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a250", content: "I am grateful to be here, still becoming.", category_id: "5", is_system: true, language: "en", tags: ["gratitude"], category: cat("gratitude") },
  { id: "a251", content: "I am creating the life I desire with every choice I make.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a252", content: "I define success on my own terms.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a253", content: "I am open to opportunities that align with my values.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a254", content: "My effort compounds. I trust the process.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a255", content: "I celebrate wins without diminishing them.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a256", content: "I learn from setbacks and keep moving with dignity.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a257", content: "I measure success by growth, integrity, and impact.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a258", content: "I am building a career and life that fit me.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a259", content: "I attract work that uses my strengths.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a260", content: "I am successful in small daily ways.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a261", content: "I finish important work with care.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a262", content: "I am open to being paid fairly for my value.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a263", content: "I pursue goals without abandoning my wellbeing.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a264", content: "I am strategic with my time and energy.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a265", content: "I let results teach me, not define my worth.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a266", content: "I am creating momentum in the direction I choose.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a267", content: "I collaborate when it multiplies good outcomes.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a268", content: "I am proud of ethical success.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a269", content: "I set ambitious goals and kind timelines.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a270", content: "I am becoming excellent through deliberate practice.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a271", content: "I share credit and own responsibility.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a272", content: "I am visible in my field in authentic ways.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a273", content: "I turn feedback into fuel.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a274", content: "I am successful because I persist with wisdom.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a275", content: "I invest in skills that free my future.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a276", content: "I am comfortable with earned recognition.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a277", content: "I build systems that support consistent results.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a278", content: "I am focused on contribution as much as achievement.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a279", content: "I choose long-term wins over short-term ego.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a280", content: "I am capable of leading projects to completion.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a281", content: "I negotiate for what I need with clarity.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a282", content: "I am creating financial steadiness step by step.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a283", content: "I align ambition with my real priorities.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a284", content: "I am resilient in competitive environments.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a285", content: "I celebrate others' success without shrinking.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a286", content: "I am the author of my professional story.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a287", content: "I ship work before it is endlessly perfect.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a288", content: "I am growing into bigger responsibilities with grace.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a289", content: "I use failure as data, not identity.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a290", content: "I am successful when I keep my word.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a291", content: "I build wealth of skill, relationship, and character.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a292", content: "I am open to unexpected doors.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a293", content: "I prepare thoroughly and trust myself in the room.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a294", content: "I am creating outcomes I once only imagined.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a295", content: "I stay humble and hungry for learning.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a296", content: "I am effective without being harsh.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a297", content: "I choose mentors and peers who elevate me.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a298", content: "I am steady in pursuit of meaningful goals.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a299", content: "I define enough as well as more.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a300", content: "I succeed in ways that let me sleep at night.", category_id: "6", is_system: true, language: "en", tags: ["success"], category: cat("success") },
  { id: "a301", content: "I offer and receive kindness with an open heart.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a302", content: "I communicate with honesty and care.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a303", content: "I attract relationships built on mutual respect.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a304", content: "I set boundaries that protect my peace and honor others.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a305", content: "I am worthy of connection that feels safe.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a306", content: "I listen fully and speak when it is true for me.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a307", content: "I repair after conflict with humility.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a308", content: "I am allowed to outgrow one-sided relationships.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a309", content: "I bring presence to the people I love.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a310", content: "I receive care without guilt.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a311", content: "I am clear about my needs without demanding.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a312", content: "I choose partners and friends who choose me back.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a313", content: "I am patient with the pace of trust.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a314", content: "I apologize sincerely when I cause harm.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a315", content: "I am affectionate in ways that feel natural to me.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a316", content: "I protect intimacy with honesty.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a317", content: "I am a safe person for others to be real with.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a318", content: "I leave room for others to be imperfect.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a319", content: "I am not responsible for managing everyone's emotions.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a320", content: "I invest in relationships that nourish both sides.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a321", content: "I speak up early instead of building resentment.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a322", content: "I am comfortable with healthy interdependence.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a323", content: "I respect no as a complete answer.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a324", content: "I am loving without losing myself.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a325", content: "I celebrate others without comparison.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a326", content: "I am available for deep conversation and light joy.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a327", content: "I choose curiosity in misunderstanding.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a328", content: "I am worthy of consistency, not crumbs.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a329", content: "I keep confidences and honor trust.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a330", content: "I am gentle in disagreement.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a331", content: "I allow people to support me.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a332", content: "I am present at the table and on the call.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a333", content: "I release relationships that require me to abandon myself.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a334", content: "I am building a community of mutual care.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a335", content: "I express appreciation often and specifically.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a336", content: "I am open to new friendships at any age.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a337", content: "I navigate family dynamics with clearer boundaries.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a338", content: "I am patient with healing in relationship patterns.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a339", content: "I choose partners who respect my autonomy.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a340", content: "I am honest about capacity and time.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a341", content: "I bring warmth without people-pleasing.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a342", content: "I am learning to be known more fully.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a343", content: "I hold space without fixing everyone.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a344", content: "I am secure enough to let others shine.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a345", content: "I create rituals of connection that fit my life.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a346", content: "I am worthy of love that is peaceful.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a347", content: "I practice gratitude for the people still here.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a348", content: "I am careful with words that cannot be unsaid.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a349", content: "I show up when it counts.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a350", content: "I am connected, not clinging.", category_id: "7", is_system: true, language: "en", tags: ["relationships"], category: cat("relationships") },
  { id: "a351", content: "I honor my body by listening to what it needs.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a352", content: "Rest is productive. I allow myself to recover.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a353", content: "I move in ways that feel good and sustainable.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a354", content: "I nourish myself with patience, not punishment.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a355", content: "I have energy for what matters when I care for the basics.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a356", content: "I am strong, resilient, and kind to my body.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a357", content: "I drink water and take breaks without negotiation.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a358", content: "I sleep as a form of self-respect.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a359", content: "I choose food that supports how I want to feel.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a360", content: "I am patient with healing timelines.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a361", content: "I move daily in a way I can maintain.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a362", content: "I listen when my body asks for stillness.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a363", content: "I am grateful for what my body can do today.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a364", content: "I release body shame and practice care.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a365", content: "I schedule rest like any important appointment.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a366", content: "I am building strength without obsession.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a367", content: "I breathe deeper when I notice shallow breath.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a368", content: "I protect my energy from constant overcommitment.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a369", content: "I am kind to my body after hard workouts and hard days.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a370", content: "I seek medical care when I need it without shame.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a371", content: "I am consistent with small health habits.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a372", content: "I stretch, walk, and pause for circulation.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a373", content: "I fuel focus with real rest, not only caffeine.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a374", content: "I am allowed to modify plans for my health.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a375", content: "I treat symptoms as information, not failure.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a376", content: "I am improving my relationship with food and movement.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a377", content: "I honor pain signals instead of overriding them always.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a378", content: "I create an evening wind-down that helps me sleep.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a379", content: "I am present in my body during daily tasks.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a380", content: "I choose posture and movement that reduce strain.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a381", content: "I am healing habits that once numbed me.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a382", content: "I celebrate non-scale victories.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a383", content: "I am patient with midlife and lifelong body changes.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a384", content: "I hydrate, breathe, and blink away from screens.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a385", content: "I am allowed to enjoy movement for joy alone.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a386", content: "I protect quiet for my nervous system.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a387", content: "I am building endurance for the life I want.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a388", content: "I take medication or treatment as prescribed with self-respect.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a389", content: "I am more than a productivity machine.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a390", content: "I rest before I am fully depleted.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a391", content: "I choose friends and spaces that support healthy living.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a392", content: "I am gentle after illness or injury.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a393", content: "I notice tension early and release it.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a394", content: "I am committed to sustainable energy, not burnout.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a395", content: "I care for mental and physical health as one.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a396", content: "I am worthy of feeling well.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a397", content: "I make the healthy choice the easier choice at home.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a398", content: "I am patient with progress that is invisible day to day.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a399", content: "I thank my body for carrying me through this day.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a400", content: "I choose health practices I can still respect next year.", category_id: "8", is_system: true, language: "en", tags: ["health"], category: cat("health") },
  { id: "a401", content: "I have survived hard days before. I can meet this one too.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a402", content: "Setbacks are part of the path. I am still on it.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a403", content: "I bend without breaking. I adapt with courage.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a404", content: "I give myself permission to feel, then to continue.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a405", content: "My past does not write my future. I do.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a406", content: "I rise again, even if slowly.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a407", content: "I am stronger than this temporary storm.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a408", content: "I learn quickly from what did not work.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a409", content: "I am allowed to start over with more wisdom.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a410", content: "I carry scars as proof of healing, not only harm.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a411", content: "I keep a thread of hope on dark days.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a412", content: "I am flexible when plans change.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a413", content: "I ask for support as an act of strength.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a414", content: "I am rebuilding with clearer boundaries.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a415", content: "I endure discomfort in service of growth.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a416", content: "I am not defined by my worst day.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a417", content: "I find solid ground one decision at a time.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a418", content: "I am resilient in mind and kind in recovery.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a419", content: "I transform pain into clearer values.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a420", content: "I keep going when results are delayed.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a421", content: "I am brave enough to try after disappointment.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a422", content: "I adapt my strategy without abandoning my goal.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a423", content: "I am soft where I need softness and firm where I need strength.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a424", content: "I survive seasons, not only moments.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a425", content: "I am patient with the nonlinear path of healing.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a426", content: "I use setbacks as redirection, not rejection.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a427", content: "I am still here, still trying, still worthy.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a428", content: "I bounce back with rest, not only grit.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a429", content: "I hold both grief and gratitude when life is complex.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a430", content: "I am resilient because I practice recovery.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a431", content: "I face hard truths without collapsing into despair.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a432", content: "I am capable of reinvention.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a433", content: "I protect hope as a daily discipline.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a434", content: "I am learning toughness that is not cruelty to myself.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a435", content: "I continue when motivation is gone and values remain.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a436", content: "I am weathered and still growing.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a437", content: "I find lessons without romanticizing harm.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a438", content: "I am steady in chaos by returning to basics.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a439", content: "I rebuild trust in myself after hard seasons.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a440", content: "I am resilient in relationships and in solitude.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a441", content: "I choose response over pure reaction more often.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a442", content: "I am alive to possibility after loss.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a443", content: "I take the next breath, then the next step.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a444", content: "I am proof that healing is possible.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a445", content: "I endure uncertainty with grounded rituals.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a446", content: "I am not done. My story continues.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a447", content: "I rise with help, not only alone.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a448", content: "I am resilient enough to rest and return.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a449", content: "I meet difficulty with a longer view.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a450", content: "I am becoming antifragile through honest practice.", category_id: "9", is_system: true, language: "en", tags: ["resilience"], category: cat("resilience") },
  { id: "a451", content: "I am fully present in this moment.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a452", content: "I observe my thoughts without judgment.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a453", content: "Peace begins with me, right here, right now.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a454", content: "I breathe deeply and return to the present.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a455", content: "This moment is enough. I am enough.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a456", content: "I notice beauty in ordinary things.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a457", content: "I arrive in my body with each breath.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a458", content: "I let go of multitasking and do one thing well.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a459", content: "I am here for this conversation, this meal, this walk.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a460", content: "I notice the pause between inhale and exhale.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a461", content: "I watch thoughts pass like weather.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a462", content: "I am awake to the life that is already happening.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a463", content: "I return from distraction without self-criticism.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a464", content: "I sense my feet, my hands, the air on my skin.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a465", content: "I am quiet enough to hear what I need.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a466", content: "I savor simple sensory pleasures.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a467", content: "I am present with discomfort without fleeing immediately.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a468", content: "I leave the phone aside for a pocket of stillness.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a469", content: "I notice tension and soften on purpose.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a470", content: "I am living this day, not only managing it.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a471", content: "I bring kind attention to whatever is arising.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a472", content: "I am rooted in now, not lost in later.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a473", content: "I practice single-task focus as care.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a474", content: "I notice the sky, the light, the temperature.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a475", content: "I am patient with a wandering mind.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a476", content: "I end the day by naming three present moments I lived.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a477", content: "I listen more than I prepare my reply.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a478", content: "I am aware of breath as an anchor.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a479", content: "I meet boredom without instantly filling it.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a480", content: "I am open to silence.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a481", content: "I notice impulses and choose a response.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a482", content: "I am embodied, not only thinking.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a483", content: "I practice gratitude as attention, not performance.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a484", content: "I am here for the ordinary miracle of being alive.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a485", content: "I release the mental rehearsal of other people's views.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a486", content: "I notice when I leave the moment and gently return.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a487", content: "I am mindful of speech before I send or say it.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a488", content: "I take one conscious breath before hard tasks.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a489", content: "I am aware of screens and choose presence.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a490", content: "I feel the ground supporting me.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a491", content: "I practice mindfulness in motion, not only sitting.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a492", content: "I am curious about my inner weather.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a493", content: "I allow stillness without needing to earn it.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a494", content: "I notice the beginning, middle, and end of a breath.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a495", content: "I am available to this moment's teaching.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a496", content: "I soften my eyes and jaw as a reset.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a497", content: "I am present with joy so it can fully register.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a498", content: "I practice coming back, not being perfect.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a499", content: "I am aware, kind, and here.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
  { id: "a500", content: "I live this hour on purpose.", category_id: "10", is_system: true, language: "en", tags: ["mindfulness"], category: cat("mindfulness") },
];

/** Free tier: first 3 per primary categories only */
export const FREE_CATEGORY_SLUGS = ["confidence", "self-love", "anxiety", "motivation", "gratitude", "success"];

export function getAffirmationsForTier(isPremium: boolean): Affirmation[] {
  if (isPremium) return ALL_AFFIRMATIONS;
  return ALL_AFFIRMATIONS.filter((a) => {
    const slug = a.category?.slug;
    if (!slug || !FREE_CATEGORY_SLUGS.includes(slug)) return false;
    const same = ALL_AFFIRMATIONS.filter((x) => x.category?.slug === slug);
    const idx = same.findIndex((x) => x.id === a.id);
    return idx >= 0 && idx < 3;
  });
}

export function getCategoriesForTier(isPremium: boolean): Category[] {
  if (isPremium) return CATEGORIES;
  return CATEGORIES.filter((c) => FREE_CATEGORY_SLUGS.includes(c.slug));
}
